set(MY_TERM $ENV{TERM})
if (MY_TERM)
   string(ASCII 27 Esc)
   string(ASCII 91 Bkt)
   set(NoColor     "${Esc}${Bkt}m")
   set(Bold        "${Esc}${Bkt}1m")
   set(ColorBold   "${Esc}${Bkt}1m")
   set(Red         "${Esc}${Bkt}31m")
   set(Green       "${Esc}${Bkt}32m")
   set(Yellow      "${Esc}${Bkt}33m")
   set(Blue        "${Esc}${Bkt}34m")
   set(Magenta     "${Esc}${Bkt}35m")
   set(Cyan        "${Esc}${Bkt}36m")
   set(White       "${Esc}${Bkt}37m")
   set(BoldRed     "${Esc}${Bkt}1;31m")
   set(BoldGreen   "${Esc}${Bkt}1;32m")
   set(BoldYellow  "${Esc}${Bkt}1;33m")
   set(BoldBlue    "${Esc}${Bkt}1;34m")
   set(BoldMagenta "${Esc}${Bkt}1;35m")
   set(BoldCyan    "${Esc}${Bkt}1;36m")
   set(BoldWhite   "${Esc}${Bkt}1;37m")
endif ()

function(log COLOR)
   list(GET ARGN 0 MessageType)
   if(MessageType STREQUAL FATAL_ERROR OR MessageType STREQUAL SEND_ERROR)
      list(REMOVE_AT ARGN 0)
   elseif(MessageType STREQUAL WARNING)
      list(REMOVE_AT ARGN 0)
   elseif(MessageType STREQUAL AUTHOR_WARNING)
      list(REMOVE_AT ARGN 0)
   elseif(MessageType STREQUAL STATUS)
      list(REMOVE_AT ARGN 0)
   else()
   endif()
   string(REPLACE ";" "" text "${ARGN}")
   message(${MessageType} "${COLOR}${text}${NoColor}")
endfunction ()
function (logred)
   log(${BoldRed} "${ARGV}")
endfunction ()
function (logyellow)
   log(${BoldYellow} "${ARGV}")
endfunction ()
